version: '3.7'

services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_ID=1
      - TOTAL_NODES=3
    volumes:
      - ./node.py:/app/node.py
    networks:
      - raft-net

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_ID=2
      - TOTAL_NODES=3
    volumes:
      - ./node.py:/app/node.py
    networks:
      - raft-net

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_ID=3
      - TOTAL_NODES=3
    volumes:
      - ./node.py:/app/node.py
    networks:
      - raft-net


networks:
  raft-net:
    driver: bridge

